apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: simple-webapp
  labels:
    app: simple-webapp
    component: backend
    tier: api
spec:
  selector:
    app: simple-webapp
    component: backend
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  type: ClusterIP
